### ISSUE TITLE
Memory leak when encrypting/decrypting

### ISSUE THREAD

**Issue by hbeckeri** [Firaenix/bsv-wasm#45] opened 2021-11-22 13:18 UTC
I have anecdotal evidence that `AES.encrypt` and `AES.decrypt` are causing a memory leak but I don't have any proof, stay sooned

**Comment by Firaenix** [comment] 2021-11-23 01:36
Maybe related https://github.com/rustwasm/wasm-bindgen/issues/1515

**Comment by Firaenix** [comment] 2021-11-24 00:28
I have been able to replicate this and I think I've identified the cause in wasm-bindgen

**Comment by Firaenix** [comment] 2021-11-27 06:48
https://github.com/rustwasm/wasm-bindgen/issues/1963

**Comment by Firaenix** [comment] 2021-11-28 10:03
Fixed in Release 1.2.2

**Closed by Firaenix** 2021-11-28 10:03 UTC
